# Generated by Django 3.0.6 on 2020-06-10 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('shortDescription', models.CharField(max_length=400)),
                ('goal', models.IntegerField()),
                ('expiredDate', models.DateField()),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('coverImage', models.ImageField(upload_to='')),
                ('fullDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationDate', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('ammount', models.FloatField()),
                ('method', models.CharField(max_length=200)),
                ('campaignID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdf.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='donation',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdf.UserDetail'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdf.UserDetail'),
        ),
    ]
