# Generated by Django 3.0.6 on 2020-06-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdf', '0002_auto_20200609_1410'),
        ('vdf', '0002_auto_20200610_1241'),
        ('vdf', '0002_auto_20200610_1127'),
    ]

    operations = [
    ]
